### PR TITLE
update URL for Virtual Hold Technology

### PR DESCRIPTION
**Pull request by adamfishman**

### CODE REVIEW

**Comment by adamfishman** [comment]
Starting to go through this list and found a broken URL

**Review by mrfright — CHANGES_REQUESTED** [review]
Thanks for finding that Adam!

Could you also update their name? I see from that link they go by just VHT now.

**Comment by adamfishman** [comment]
you got it!

**Comment by mrfright** [comment]
Thanks! Figured change that while we're at it.

**Pull request merged**
